#some basic plots
library(tidyverse)
library(sf)
library(lubridate)
library(deltamapr)
library(readxl)
library(wql)

#The summarized zooplankton data were generated by the zoops_datamanip.R file
load("data/ZoopsSum.RData")
load("data/ZoopsSumm.RData")
load("data/lilzoopsmean.RData")
load("data/ZoopsSumMM2.RData")
taxa = read_excel("Data/taxa.xlsx")

source("HelperFuncitons.R")

Regions<-read_csv("data/Rosies_regions.csv")

Delta<-deltamapr::R_EDSM_Subregions_Mahardja_FLOAT%>%
  filter(SubRegion%in%unique(Regions$SubRegion))%>%  #Filter to regions of interest
  dplyr::select(SubRegion)

Regs = unique(Regions[,c(1,5)])
Delta = merge(Delta, Regs)


#I'd also like some descriptive plots, if possible
ZS_life = mutate(ZoopsSumLifestage, Taxlifestage = paste(Taxname2, Lifestage)) %>%
  filter(Taxlifestage %in% c(taxa$Taxlifestage))
ZS_life2 = mutate(ZoopsSumm_lifestage, Taxlifestage = paste(Taxname2, Lifestage)) %>%
  filter(Taxlifestage %in% c(taxa$Taxlifestage))
Hyp = filter(ZoopsSumMM2, Taxname2 == "Hyperacanthomysis longirostris") %>%
  mutate(Taxlifestage = "Hyperacanthomysis longirostris")

ZS = bind_rows(ZS_life, ZS_life2, Hyp) %>%
  group_by(Month, Region, Season, Year, Taxlifestage) %>%
  summarize(CPUE = mean(CPUE, na.rm =T)) %>%
  left_join(WQ_dataNARM, by = c("Month", "Year", "Region")) %>%
  left_join(lilzoopsmean) %>%
  mutate_all( ~ case_when(!is.nan(.x) ~ .x)) %>%
  ungroup() %>%
  mutate(SalSurf = ec2pss(Conductivity/1000, t=25),
         logChl = log(Chlorophyll),
         logCPUE = log(CPUE +1),
         rCPUE = round(CPUE)) %>%
  left_join(dplyr::select(taxa, Taxlifestage, shortname))
  

ggplot(ZS, aes(x = Month, y = logCPUE))+
  geom_point(aes(color = Year), alpha = 0.2)+
  scale_color_viridis_c(option = "A")+
  geom_smooth(color = "black")+
  facet_wrap(~shortname)+
  theme_bw()

ggplot(ZS, aes(x = Month, y = logCPUE))+
  geom_point(aes(color = SalSurf), alpha = 0.2)+
  scale_color_viridis_c(option = "C")+
  geom_smooth(color = "black")+
  facet_wrap(~shortname)+
  theme_bw()


#OK, now salinity patterns

ggplot(ZS, aes(x = SalSurf, y = logCPUE))+
  geom_point(aes(color = Month), alpha = 0.2)+
  scale_color_viridis_c(option = "C")+
  geom_smooth(color = "black")+
  facet_wrap(~shortname)


#OK, now chlorophyll patterns

ggplot(ZS, aes(x = logChl, y = logCPUE))+
  geom_point(aes(color = Month), alpha = 0.2)+
  scale_color_viridis_c(option = "C")+
  geom_smooth(color = "black")+
  facet_wrap(~shortname)+
  coord_cartesian(xlim = c(-.5,3))+
  theme_bw()


ggplot(ZS, aes(x = Secchi, y = logCPUE))+
  geom_point(aes(color = Month), alpha = 0.2)+
  scale_color_viridis_c(option = "C")+
  geom_smooth(color = "black")+
  facet_wrap(~shortname)+
  coord_cartesian(xlim = c(0,200))

library(corrplot)

predictors = dplyr::select(ZS, logChl, Secchi, SalSurf, lilzoopbiomass) %>%
  filter(!is.na(logChl), !is.na(Secchi), !is.na(SalSurf), !is.na(lilzoopbiomass)) %>%
  distinct()

#correlation plot of predictor variables
predcor = cor(predictors)
corrplot(predcor)
corrplot.mixed(predcor, lower.col = c( "blue","red"), 
               upper.col =colorRampPalette(c("blue","white","red"))(200),
               tl.col = "black")


#now a correlation plot of everything, because why not?

zoopwide = pivot_wider(ZS, id_cols = c(Month, Year, Region, SalSurf, Secchi, logChl, lilzoopbiomass), names_from = shortname,
                       values_from = CPUE)%>%
  filter(!is.na(logChl), !is.na(Secchi), !is.na(SalSurf), !is.na(lilzoopbiomass)) %>%
  distinct()


cor2 = cor(zoopwide[,4:23])
corrplot.mixed(cor2, lower.col = c( "blue","red"), 
               upper.col =colorRampPalette(c("blue","white","red"))(200),
               tl.col = "black", tl.pos = "lt")


#OK, apparently Synchaeata aren't as strictly predatory as a I thoguht. It varies by species.
#But what species do we have here?

synchea = Zoopsynther(Data_type = "Taxa", Size_class = "Micro", Taxa = "Synchaeta")
