#New version of the analysis for reboot of project.

#just use the 5 months of greatest abundance
#three taxa from each functional group
#linear models are better.

library(tidyverse)
library(lme4)
library(lmerTest)
#library(MASS)
library(glmmTMB)
library(DHARMa)
library(performance)
library(car)
library(zooper)
library(effects)
library(MuMIn)
library(wql)
library(deltamapr)
library(sf)
library(wql)
library(corrplot)
library(ggh4x)
library(scales)

#The summarized zooplankton data were generated by the zoops_datamanip.R file
load("data/ZoopsSum.RData")
load("data/ZoopsSumm.RData")
load("data/lilzoopsmean.RData")
load("data/ZoopsSumMM2.RData")
source("HelperFuncitons.R")

#Note: i tried a lag of chlorophyll a earlier and it didn't work very well
#start with Pseudodiaptomus

Regions<-read_csv("data/Rosies_regions.csv")

Delta<-deltamapr::R_EDSM_Subregions_Mahardja_FLOAT%>%
  filter(SubRegion%in%unique(Regions$SubRegion))%>%  #Filter to regions of interest
  dplyr::select(SubRegion)

Regs = unique(Regions[,c(1,5)])
Delta = merge(Delta, Regs)


#start with p. forbesi adults. just the appropraite salinity range, most abundant months


Pseudox_juv = Filters_LS("Pseudodiaptomus_UnID", "Juvenile", ZoopsSumLifestage)

Pseudox_ad = Filters_LS("Pseudodiaptomus forbesi", "Adult", ZoopsSumLifestage)

Eury_juv = Filters_LS("Eurytemora affinis", "Juvenile", data =ZoopsSumLifestage)

Eury_ad = Filters_LS("Eurytemora affinis", "Adult", data = ZoopsSumLifestage)

Limno_juv = Filters_LS("Limnoithona", "Juvenile", data = ZoopsSumm_lifestage)

Limno_ad = Filters_LS("Limnoithona", "Adult", data = ZoopsSumm_lifestage)

Tort_juv = Filters_LS( "Tortanus_UnID" , "Juvenile", data = ZoopsSumLifestage)

Tort_ad = Filters_LS( "Tortanus_UnID" , "Adult", data = ZoopsSumLifestage)

#acartiella juveniles weren't speticated until after 2005
Acart_juv = Filters_LS( "Acartiella_UnID" , "Juvenile", data = ZoopsSumLifestage)%>%
  filter( Year >2005)
Acart_ad = Filters_LS( "Acartiella_UnID" , "Adult", data = ZoopsSumLifestage) %>%
  filter(Year >2005)

Acan = Filters("Acanthocyclops_UnID", data = ZoopsSum)
Bos = Filters("Bosmina longirostris", data = ZoopsSum)
Sync = Filters("Synchaeta", data = ZoopsSumm)
Daph = Filters("Daphnia_UnID", data = ZoopsSum)
Kerat = Filters("Keratella", data = ZoopsSumm)

Hyp2 = Filters("Hyperacanthomysis longirostris", data = ZoopsSumMM2)

allzoops = bind_rows(Pseudox_juv, Pseudox_ad, Eury_juv, Eury_ad,
                     Limno_juv, Limno_ad, Tort_juv, Tort_ad, Acart_juv, Acart_ad, Acan,
                     Bos, Sync, Daph, Kerat, Hyp2) %>%
  mutate(Taxlifestage = paste(Taxname2, Lifestage))

save(allzoops,Pseudox_juv, Pseudox_ad, Eury_juv, Eury_ad,
     Limno_juv, Limno_ad, Tort_juv, Tort_ad, Acart_juv, Acart_ad, Acan,
     Bos, Sync, Daph, Kerat, Hyp2, Delta, file = "data/filteredzoopData.RData")
load("data/filteredzoopData.RData")

#################################################################

#quick exploritory plots
hist(Pseudox_ad$CPUE)
hist(log(Pseudox_ad$CPUE +1))


ggplot(Pseudox_ad, aes(x = Year, y = logCPUE)) + geom_point() 
ggplot(Pseudox_ad, aes(x = as.factor(Month), y = logCPUE)) + geom_boxplot() + facet_wrap(~Region)
ggplot(Pseudox_ad, aes(x = SalSurf, y = logCPUE)) + geom_point() + facet_wrap(~Region)



#what salinity range for each?

allzoopsal = group_by(allzoops, Taxlifestage) %>%
  summarize(sal = mean(SalSurf), maxsal = max(SalSurf), minsal = min(SalSurf), medsal = median(SalSurf))

###############################################################
#now implement the zoopdredger funciton

#basic model, chlorophyll, secchi, salinity
#first adults
p5 = Zoopdredger(Pseudox_ad)
summary(p5)
plot(simulateResiduals(p5))
testZeroInflation(p5)

#Now juveniles
p5j = Zoopdredger(Pseudox_juv)
summary(p5j)
plot(simulateResiduals(p5j))
testZeroInflation(p5j)


#add little zoops
p5l = Zoopdredger2(Pseudox_ad)

summary(p5l)
plot(simulateResiduals(p5l))
testZeroInflation(p5l)

#add little zoops
p5lj = Zoopdredger2(Pseudox_juv)

summary(p5lj)


######################################################


#Eurytemora
e5 = Zoopdredger(Eury_ad)
summary(e5)
plot(simulateResiduals(e5))
testZeroInflation(e5)

#add little zoops
e5l = Zoopdredger2(Eury_ad)

summary(e5l)
plot(simulateResiduals(e5l))
testZeroInflation(e5l)
#pesudos can eat everything, so no effect of chlorophyll, eurys much more narrow diet, 

#juvenils
e5j = Zoopdredger(Eury_juv)
summary(e5j)
plot(simulateResiduals(e5j))
testZeroInflation(e5j)

#add little zoops
e5lj = Zoopdredger2(Eury_juv)

summary(e5lj)
plot(simulateResiduals(e5lj))

########################################################################

#Acanthocyclops
a5 = Zoopdredger(Acan)
summary(a5)
plot(simulateResiduals(a5))
testZeroInflation(a5)

#add little zoops
a5l = Zoopdredger2(Acan)

summary(a5l)
plot(simulateResiduals(a5l))
testZeroInflation(a5l)

######################################################################
#Acartiella
#Acartiella copepodids weren't seperated until 2006, so I'm going to subset
#to just that time period.

ac5 = Zoopdredger(Acart_ad)
summary(ac5)
plot(simulateResiduals(ac5))
testZeroInflation(ac5)

#add little zoops
ac5l = Zoopdredger2(Acart_ad)

summary(ac5l)
plot(simulateResiduals(ac5l))


#juveniles
ac5j = Zoopdredger(Acart_juv)
summary(ac5j)
plot(simulateResiduals(ac5j))
testZeroInflation(ac5j)

#add little zoops
ac5lj = Zoopdredger2(Acart_juv)

summary(ac5lj)
plot(simulateResiduals(ac5lj))


###################################################################
#Bosmina


b5 = Zoopdredger(Bos)
summary(b5)
plot(simulateResiduals(b5))
testZeroInflation(b5)

#add little zoops
b5l = Zoopdredger2(Bos)

summary(b5l)
plot(simulateResiduals(b5l))


###################################################################
#Daphnia

hist(Daph$CPUE)
hist(log(Daph$CPUE +1))
#hm.

d5 = Zoopdredger(Daph)
summary(d5)
plot(simulateResiduals(d5))


#add little zoops
d5l = Zoopdredger2(Daph)

summary(d5l)
plot(simulateResiduals(d5l))

###################################################################
#Tortanus

  

hist(Tort_ad$CPUE)
hist(log(Tort_ad$CPUE +1))
#hm.
hist(Daph$CPUE)
hist(log(Daph$CPUE +1))
#hm.

t5 = Zoopdredger(Tort_ad)
summary(t5)
plot(simulateResiduals(t5))


#add little zoops
t5l = Zoopdredger2(Tort_ad)

summary(t5l)
plot(simulateResiduals(t5l))

#Juveniles
t5j = Zoopdredger(Tort_juv)
summary(t5j)
plot(simulateResiduals(t5j))


#add little zoops
t5lj = Zoopdredger2(Tort_juv)

summary(t5lj)
plot(simulateResiduals(t5lj))

################################################


#hm.

l5 = Zoopdredger(Limno_ad)
summary(l5)
plot(simulateResiduals(l5))


#add little zoops
l5l = Zoopdredger2(Limno_ad)

summary(l5l)
plot(simulateResiduals(l5l))

#Juveniles
l5j = Zoopdredger(Limno_juv)
summary(l5j)
plot(simulateResiduals(l5j))


#add little zoops
l5lj = Zoopdredger2(Limno_juv)

summary(l5lj)
plot(simulateResiduals(l5lj))

################################################

#####################################################################
#Some random rotifer

hist(Kerat$CPUE)
hist(log(Kerat$CPUE +1))
#perfectly bell-shaped except for the zeros


k5 = Zoopdredger(Kerat)
summary(k5)
plot(simulateResiduals(k5))

########################################################################
#another rotifer
hist(Sync$CPUE)
hist(log(Sync$CPUE +1))
#perfectly bell-shaped except for the zeros

s5 = Zoopdredger(Sync)
summary(s5)
plot(simulateResiduals(s5))


#################################################################
#Hyperacanthomysis logirostris


hist(Hyp2$CPUE)
hist(log(Hyp2$CPUE+1))
# a little flat and zero-inflated, bu tnot bad


h5 = Zoopdredger(Hyp2)
summary(h5)
plot(simulateResiduals(h5))


#add little zoops
h5l = Zoopdredger2(Hyp2)

summary(h5l)
plot(simulateResiduals(h5l))

save.image()

#########################################################################

save(p5, p5l, p5lj,  p5j, e5, e5l,  e5j, e5lj, b5, b5l, d5, d5l, l5lj, l5l, l5, l5j,
     a5, a5l, ac5, ac5l, ac5j, ac5lj, t5, t5j, t5l, t5lj,  h5, h5l, s5,k5, file = "outputs/SpeciesModels_30may2024.RData")
load("outputs/SpeciesModels_30may2024.RData")

#################################################################################
#OK, now I need a way of displaying all these predictors and parameters and stuff in a 
#way that makes sense. I'm going to have to think about this. 

agrigate = bind_rows(getcoefs(p5, "P. forbesi adult"),
                     getcoefs(p5j, "Pseudodiaptomus sp. juvenile"),
                     getcoefs(e5, "E. carolleeae adult"),
                     getcoefs(e5j, "E. carolleeae juvenile"),
                     getcoefs(t5, "Tortanus sp. adult"),
                     getcoefs(t5j, "Tortanus sp. juvenile"),
                     getcoefs(d5, "Daphnia sp."),
                     getcoefs(b5, "B. logirostris"),
                     getcoefs(k5, "Kerottela sp."),
                     getcoefs(l5, "Limnoithona sp. adult"),
                     getcoefs(l5j, "Limnoithona sp. juvenile"),
                     getcoefs(h5, "H. logirostris"),
                     getcoefs(ac5, "A. sinensis adult"),
                     getcoefs(ac5j, "A. sinensis juvenile"),
                     getcoefs(s5, "Syncheata sp."),
                     getcoefs(a5, "Acanthocyclops sp."))%>%
  mutate(pp = paste(paramtype, params))

test = agrigate  %>%
  pivot_wider(id_cols = Species, names_from = pp, values_from = Estimate) %>%
  pivot_longer(cols = 2:last_col(), names_to = "pp", values_to = "Estimate")


test2 = left_join(test, agrigate)

arg= str_split_fixed(test2$pp, " ", n = 2)
test3 = cbind(test2, arg) %>%
  rename(Paramtype = `1`, Param = `2`) %>%
  mutate(params = NULL, paramtype = NULL, Estimate2 = case_when(
    `Pr(>|z|)` < 0.05 & Estimate < 0 ~ "Decrease",
    `Pr(>|z|)` < 0.05 & Estimate >0 ~ "Increase",
    `Pr(>|z|)` > 0.05 ~ "Not Significant",
    TRUE ~ "Not Included"
  ), ParamX = factor(Param, levels = c("(Intercept)", "SalSurfsc", "Secchisc",
                                                        "logChlsc", "lilzoops"),
                                      labels = c("Intercept", "Salinity", "Secchi Depth", 
                                                  "Chlorophyll", "Microzooplankton")),
               Paramtype = factor(Paramtype, levels = c("count", "zi"), labels =
                                    c("Count", "Zero Inflation")))

#Get size classes and groups to sort by
library(readxl)
taxa = read_excel("Data/taxa.xlsx")

test3 = left_join(test3, taxa, by = c("Species"= "Taxon")) %>%
  mutate(Estimate2 = case_when(ParamX == "Microzooplankton" & Species %in% c("Kerottela sp.","Syncheata sp.") ~ "Not Tested",
                               TRUE ~ Estimate2))

ggplot(filter(test3, !is.na(Paramtype)), 
       aes(x = ParamX, y = Species, fill = Estimate2)) + geom_tile() +
   facet_grid(~Paramtype, scales = "free", space = "free") +
  scale_fill_manual(values = c("lightblue", "red", "grey", "white", "grey20"), name = "Model \nEstimate") +
  ylab(NULL) + xlab(NULL)+
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
  facetted_pos_scales(y = list(scale_y_discrete(labels = taxlabelsH),
                               scale_y_discrete(labels = taxlabelsO),
                               scale_y_discrete(labels = taxlabelsP)))+
  
  geom_text(aes(label = round(Estimate, dig = 2)))+
  facet_grid(FeedingGuild~Paramtype, scales = "free", space = "free")


ggsave("plots/modelmatrix.tiff", device = "tiff", width =7, height =8)



#Point plot with standard error
ggplot(filter(test3,Paramtype == "Count", ParamX != "Intercept"), 
       aes(x = Species, y = Estimate, color = ParamX)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = Estimate- `Std. Error`, ymax = Estimate + `Std. Error`))+
  facet_wrap(~ParamX, scales = "free_y")+
  scale_alpha_manual(values = c(0.3, 1))+ 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust =0.5, hjust = 1), legend.position = "none")
  

ggsave("plots/pointplot.tiff", device = "tiff", width =8, height =5)
############################################################################

#with microzoops

agrigatel = bind_rows(getcoefs(p5l, "P. forbesi adult"),
                     getcoefs(p5lj, "Pseudodiaptomus sp. juvenile"),
                     getcoefs(e5l, "E. carolleeae adult"),
                     getcoefs(e5lj, "E. carolleeae juvenile"),
                     getcoefs(t5l, "Tortanus sp. adult"),
                     getcoefs(t5lj, "Tortanus sp. juvenile"),
                     getcoefs(d5l, "Daphnia sp."),
                     getcoefs(b5l, "B. logirostris"),
                     getcoefs(k5, "Kerottela sp."),
                     getcoefs(l5l, "Limnoithona sp. adult"),
                     getcoefs(l5lj, "Limnoithona sp. juvenile"),
                     getcoefs(h5l, "H. logirostris"),
                     getcoefs(ac5l, "A. sinensis adult"),
                     getcoefs(ac5lj, "A. sinensis juvenile"),
                     getcoefs(s5, "Syncheata sp."),
                     getcoefs(a5l, "Acanthocyclops sp."))%>%
  mutate(pp = paste(paramtype, params))

testl = agrigatel  %>%
  pivot_wider(id_cols = Species, names_from = pp, values_from = Estimate) %>%
  pivot_longer(cols = 2:last_col(), names_to = "pp", values_to = "Estimate")


test2l = left_join(testl, agrigatel)

argl= str_split_fixed(test2l$pp, " ", n = 2)
test3l = cbind(test2l, argl) %>%
  rename(Paramtype = `1`, Param = `2`) %>%
  mutate(params = NULL, paramtype = NULL, Estimate2 = case_when(
    `Pr(>|z|)` < 0.05 & Estimate < 0 ~ "Decrease",
    `Pr(>|z|)` < 0.05 & Estimate >0 ~ "Increase",
    `Pr(>|z|)` > 0.05 ~ "Not Significant",
    TRUE ~ "Not Included"
  ), ParamX = factor(Param, levels = c("(Intercept)", "SalSurfsc", "Secchisc",
                                       "logChlsc", "lilzoops"),
                     labels = c("Intercept", "Salinity", "Secchi Depth", 
                                "Chlorophyll", "Microzooplankton")),
  Paramtype = factor(Paramtype, levels = c("count", "zi"), labels =
                       c("Count", "Zero Inflation")))


test3l = left_join(test3l, taxa, by = c("Species"= "Taxon")) %>%
  mutate(Estimate2 = case_when(ParamX == "Microzooplankton" & Species %in% c("Kerottela sp.","Syncheata sp.") ~ "Not Tested",
                               TRUE ~ Estimate2))

ggplot(filter(test3l, !is.na(Paramtype)), 
       aes(x = ParamX, y = Species, fill = Estimate2)) + geom_tile() +
  scale_fill_manual(values = c("lightblue", "red", "grey", "white", "grey20"), name = "Model \nEstimate") +
  ylab(NULL) + xlab(NULL)+
  #scale_y_discrete(labels = taxalabels)+
  facet_grid(FeedingGuild~Paramtype, scales = "free", space = "free")+
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
  facetted_pos_scales(y = list(scale_y_discrete(labels = taxlabelsH),
                               scale_y_discrete(labels = taxlabelsO),
                              scale_y_discrete(labels = taxlabelsP)))+
  geom_text(aes(label = round(Estimate, dig = 2)))
  

ggsave("plots/modelmatrix_wMicro.tiff", device = "tiff", width =7, height =8)

#Point plot with standard error
ggplot(filter(test3l,Paramtype == "Count", ParamX != "Intercept"), 
       aes(x = Species, y = Estimate, color = ParamX)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = Estimate- `Std. Error`, ymax = Estimate + `Std. Error`))+
  facet_wrap(~ParamX, scales = "free_y")+
  scale_alpha_manual(values = c(0.3, 1))+ 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust =1, vjust = .5), legend.position = "none")



ggsave("plots/pointplot_wmicro.tiff", device = "tiff", width =7, height =6)

########################################################################
#now one example of an effects plot from each feeding guilde


effectsfun = function(mod, data) {
  dataset = data
  effs = allEffects(mod, xlevels = 10)
  df = data.frame(NA) 
  for(i in 1:length(effs)){
    df2 = data.frame(effs[[i]]) %>%
      mutate(param = names(effs)[i])
    names(df2) = c("level", "fit", "se", "lower", "upper", "param")
    df = bind_rows(df, df2)
  }
  df$taxa = if("Lifestage" %in% names(dataset)) paste(unique(dataset$Taxname2), unique(dataset$Lifestage)) else unique(dataset$Taxname2)
    
  df = mutate(df, levelx = case_when(
    param == "logChlsc" ~ exp(level* sd(dataset$logChl, na.rm =T) + mean(dataset$logChl, na.rm =T)),
    param == "lilzoops" ~ exp(level*sd(log(dataset$lilzoopbiomass+1), na.rm =T) + mean(log(dataset$lilzoopbiomass+1), na.rm =T)),
    param == "Secchisc" ~ level*sd(dataset$Secchi, na.rm =T) + mean(dataset$Secchi, na.rm =T),
    param == "SalSurfsc" ~ exp(level*sd(log(dataset$SalSurf), na.rm =T) + mean(log(dataset$SalSurf), na.rm =T))))
  
  return(df)
}

#ugh, this is annoying. 

dataset = Pseudox_ad
ppp = effectsfun(p5l, Pseudox_ad)

#the upper CI for the first level of Psudodiaptomus is so high you can't see what is going on.
#there is no real way to change the scales manuyally, so I'm going to adujut it here and make a note in the caption
ppp[2,"upper"] = 5000
ppp[3,"upper"] = 5000


dataset = Limno_ad
lll = effectsfun(l5l, Limno_ad)

dataset = Acan
AAA = effectsfun(a5l, Acan)

dataset = Eury_ad
eee = effectsfun(e5l, Eury_ad)

effectsall = bind_rows(ppp, lll, AAA, eee) %>%
  dplyr::select(-NA.) %>%
  filter(!is.na(param))



#something is weird with the x-axis on salsurf
ggplot(effectsall, aes(x = level, y = fit))+ 
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.4)+
  geom_smooth()+
  facet_grid(taxa~param, scales = "free")


effectsall = mutate(effectsall, Parameter = fct_recode(param, "Microzooplankton (mg/L)" = "lilzoops",
                                                       "Chlorophyll (ug/L)" = "logChlsc",
                                                       "Salinity (PSU)" = "SalSurfsc",
                                                       "Secchi (cm)" = "Secchisc"),
                    Taxa = fct_recode(taxa, "Acanthocyclops sp." = "Acanthocyclops_UnID",
                                      "E. carolleeae adult" = "Eurytemora affinis",
                                      "Limnoithona sp. adult" = "Limnoithona",
                                      "P. forbesi adult" = "Pseudodiaptomus forbesi"),
                    levelx = case_when(param == "lilzoops" ~ levelx/1000,
                                    TRUE ~ levelx),
                    paramtax = paste(Parameter, Taxa))

#blank squares for predictors that weren's included

blanksx = group_by(effectsall, Parameter) %>%
  summarize(xmin = 0, xmax = max(levelx, na.rm =T))

blanksy = group_by(effectsall, Taxa) %>%
  summarize(ymin = 0, ymax = max(upper, na.rm =T))

blanks = merge(blanksx, blanksy) %>%
  mutate(paramtax = paste(Parameter, Taxa)) %>%
  filter(!paramtax %in% effectsall$paramtax) %>%
  mutate(Label = "Not Included")

     #    Include = case_when(paramtax %in% effectsall$paramtax ~FALSE,
      #   TRUE ~ TRUE)) %>%
  

#Effects plot for paper
ggplot(effectsall, aes(x = levelx, y = fit))+ 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.4, fill = "skyblue")+
  geom_line()+
  facet_grid(Taxa~Parameter, scales = "free")+
  geom_rect(data = blanks, aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
            inherit.aes = FALSE, alpha = 0.4)+
  geom_text(data = blanks, aes(x = (xmax-xmin)/2, y = (ymax-ymin)/2, label = Label), inherit.aes = FALSE)+
  ylab("Partial Residuals")+
  xlab("Value of Predictor variable")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust =1, hjust =1))

ggsave("plots/EffectsPlot.tiff", device = "tiff", width =8, height =6.5)


######################################################################
#extra effects plots for supplemental information



dataset = Limno_juv
lllj = effectsfun(l5lj, Limno_juv)

dataset = Acart_ad
ACC = effectsfun(ac5l, Acart_ad)

dataset = Acart_juv
ACCj = effectsfun(ac5lj, Acart_juv)


dataset = Eury_juv
eeej = effectsfun(e5lj, Eury_juv)

dataset = Bos
BBB = effectsfun(b5l, Bos)

dataset = Daph
DDD = effectsfun(d5l, Daph)

dataset = Hyp2
HHH = effectsfun(h5l, Hyp2)

dataset = Pseudox_juv
pppj = effectsfun(p5lj, Pseudox_juv)

dataset = Sync
sss = effectsfun(s5, Sync)

dataset = Kerat
kkk = effectsfun(s5, Sync)

dataset = Tort_ad
TTT = effectsfun(t5l, Tort_ad)

dataset = Tort_juv
TTTj = effectsfun(t5lj, Tort_juv)



effectsall = bind_rows(ppp, pppj, lll, lllj, AAA, ACC, ACCj, eee, eeej, DDD, BBB, HHH, kkk, TTT, TTTj) %>%
  dplyr::select(-NA.) %>%
  filter(!is.na(param))


effectsall = mutate(effectsall, Parameter = fct_recode(param, "Microzooplankton (mg/L)" = "lilzoops",
                                                       "Chlorophyll (ug/L)" = "logChlsc",
                                                       "Salinity (PSU)" = "SalSurfsc",
                                                       "Secchi (cm)" = "Secchisc"),
                    Taxa = fct_recode(taxa, "Acanthocyclops spp." = "Acanthocyclops_UnID",
                                      "E.carolleeae adult" = "Eurytemora affinis Adult",
                                      "Limnoithona spp. adult" = "Limnoithona Adult",
                                      "P.forbesi adult" = "Pseudodiaptomus forbesi Adult",
                                      "Pseudodiaptomus spp. juv" ="Pseudodiaptomus_UnID Juvenile",
                                      "Tortanus spp. adult" = "Tortanus_UnID Adult",
                                      "Tortanus spp. juv" ="Tortanus_UnID Juvenile",
                                      "A. sinensis adult" ="Acartiella_UnID Adult",
                                      "A. sinensis juv" ="Acartiella_UnID Juvenile",
                                      "Daphnia spp." = "Daphnia_UnID"),
                    levelx = case_when(param == "lilzoops" ~ levelx/1000,
                                       TRUE ~ levelx),
                    paramtax = paste(Parameter, Taxa))

#blank squares for predictors that weren's included

blanksx = group_by(effectsall, Parameter) %>%
  summarize(xmin = 0, xmax = max(levelx, na.rm =T))

blanksy = group_by(effectsall, Taxa) %>%
  summarize(ymin = 0, ymax = max(upper, na.rm =T))

blanks = merge(blanksx, blanksy) %>%
  mutate(paramtax = paste(Parameter, Taxa)) %>%
  filter(!paramtax %in% effectsall$paramtax) %>%
  mutate(Label = "Not Included")

#    Include = case_when(paramtax %in% effectsall$paramtax ~FALSE,
#   TRUE ~ TRUE)) %>%


#Effects plot for paper
ggplot(filter(effectsall, Taxa %in% unique(effectsall$Taxa)[1:8]), aes(x = levelx, y = fit))+ 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.4, fill = "skyblue")+
  geom_line()+
  facet_grid(Taxa~Parameter, scales = "free")+
  geom_rect(data = filter(blanks,Taxa %in% unique(effectsall$Taxa)[1:8]),
            aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
            inherit.aes = FALSE, alpha = 0.4)+
  geom_text(data = filter(blanks,Taxa %in% unique(effectsall$Taxa)[1:8]), 
                          aes(x = (xmax-xmin)/2, y = (ymax-ymin)/2, label = Label), inherit.aes = FALSE)+
  ylab("Partial Residuals")+
  xlab("Value of Predictor variable")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust =1, hjust =1))

ggsave("plots/EffectsPlot_1.tiff", device = "tiff", width =8, height =10)



ggplot(filter(effectsall, Taxa %in% unique(effectsall$Taxa)[9:15]), aes(x = levelx, y = fit))+ 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.4, fill = "skyblue")+
  geom_line()+
  facet_grid(Taxa~Parameter, scales = "free")+
  geom_rect(data = filter(blanks,Taxa %in% unique(effectsall$Taxa)[9:15]),
            aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax), 
            inherit.aes = FALSE, alpha = 0.4)+
  geom_text(data = filter(blanks,Taxa %in% unique(effectsall$Taxa)[9:15]), 
            aes(x = (xmax-xmin)/2, y = (ymax-ymin)/2, label = Label), inherit.aes = FALSE)+
  ylab("Partial Residuals")+
  xlab("Value of Predictor variable")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust =1, hjust =1))

ggsave("plots/EffectsPlot_2.tiff", device = "tiff", width =8, height =8)

#########################################################################
#floweffects
pflow = Zoopdredger3(Pseudox_ad)
plot(allEffects(pflow))
pflowj = Zoopdredger3(Pseudox_juv)
eflow = Zoopdredger3(Eury_ad)
eflowj = Zoopdredger3(Eury_juv)
bflow = Zoopdredger3(Bos)
dflow = Zoopdredger3(Daph)
lflow = Zoopdredger3(Limno_ad)
lflowj = Zoopdredger3(Limno_juv)
aflow = Zoopdredger3(Acan)
acflow = Zoopdredger3(Acart_ad)
acflowj = Zoopdredger3(Acart_juv)
sflow = Zoopdredger3(Sync)
tflow = Zoopdredger3(Tort_ad)
tflowj = Zoopdredger3(Tort_juv)
kflow = Zoopdredger3(Kerat)
hflow = Zoopdredger3(Hyp2)

save(pflow, pflowj, eflow, eflowj, bflow, dflow, lflow, lflowj, aflow, acflow, acflowj, sflow, tflow, tflowj, kflow, hflow,
     file = "outputs/flowmodels.RData")

agrigateflow = bind_rows(getcoefs(pflow, "Pseudodiaptomus adult"),
                         getcoefs(pflowj, "Pseudodiaptomus juvenile"),
                     getcoefs(eflow, "Eurytemora adult"),
                     getcoefs(eflowj, "Eurytemora juvenile"),
                     getcoefs(tflow, "Tortanus adult"),
                     getcoefs(tflowj, "Tortanus juvenile"),
                     getcoefs(dflow, "Daphnia"),
                     getcoefs(bflow, "Bosmina"),
                     getcoefs(kflow, "Kerottela"),
                     getcoefs(lflow, "Limnoithona adult"),
                     getcoefs(lflowj, "Limnoithona juvenile"),
                     getcoefs(hflow, "H. Logirostris"),
                     getcoefs(aflow, "Acanthocyclops"),
                     getcoefs(sflow, "Syncheata"),
                     getcoefs(acflow, "Acartiella adult"),
                     getcoefs(acflowj, "Acartiella juvenile"))%>%
  mutate(pp = paste(paramtype, params))

test = agrigateflow  %>%
  pivot_wider(id_cols = Species, names_from = pp, values_from = Estimate) %>%
  pivot_longer(cols = 2:last_col(), names_to = "pp", values_to = "Estimate")


test2f = left_join(test, agrigateflow)

arg= str_split_fixed(test2f$pp, " ", n = 2)
test3f = cbind(test2f, arg) %>%
  rename(Paramtype = `1`, Param = `2`) %>%
  mutate(params = NULL, paramtype = NULL, Estimate2 = case_when(
    `Pr(>|z|)` < 0.05 & Estimate < 0 ~ "Decrease",
    `Pr(>|z|)` < 0.05 & Estimate >0 ~ "Increase",
    `Pr(>|z|)` > 0.05 ~ "Not Significant",
    TRUE ~ "Not Included"
  ))

ggplot(filter(test3f, Param != "(Intercept)"), aes(x = Species, y = Param, fill = Estimate)) + geom_tile() +
  facet_wrap(~Paramtype) +
  scale_fill_gradient2()


test3f = mutate(test3f, ParamX = factor(Param, levels = c("(Intercept)", "log(SalSurf)", "Secchisc",
                                                        "logChlsc", "logout", "lilzoops"),
                                      labels = c("Intercept", "Salinity", "Secchi Depth", 
                                                 "Chlorophyll", "Outflow", "Microzooplankton")),
               Paramtype = factor(Paramtype, levels = c("count", "zi"), labels =
                                    c("Count", "Zero Inflation")))


#Get size classes and groups to sort by
library(readxl)
taxa = read_excel("Data/taxa.xlsx")

test3f = left_join(test3f, taxa, by = c("Species"= "Taxon")) 

ggplot(filter(test3f, !is.na(Paramtype)), 
       aes(x = ParamX, y = Species, fill = Estimate2)) + geom_tile() +
  facet_grid(~Paramtype, scales = "free_x", space = "free") +
  scale_fill_manual(values = c("lightblue", "red", "grey", "white", "grey20"), name = "Model \nEstimate") +
  ylab(NULL) + xlab(NULL)+
  scale_y_discrete(lables = taxalabels)+
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
  geom_text(aes(label = round(Estimate, dig = 2)))+
  facet_grid(FeedingGuild~Paramtype, scales = "free", space = "free")

ggsave("plots/modelmatrix_wflow.tiff", device = "tiff", width =7, height =8)


#Point plot with standard error
ggplot(filter(test3f,Paramtype == "Count", ParamX != "Intercept"), 
       aes(x = Species, y = Estimate, color = ParamX)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = Estimate- `Std. Error`, ymax = Estimate + `Std. Error`))+
  facet_wrap(~ParamX, scales = "free_y")+
  scale_alpha_manual(values = c(0.3, 1))+ 
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust =1, vjust = .5), legend.position = "none")



ggsave("plots/pointplot_wflow.tiff", device = "tiff", width =8, height =6)



 #Meh, keeping salinity in there makes more sense. Using both is problematic, and there weren't any situations where flow was better than salinity
#######################################################

##########################################################################################

#look at correlations between predictor variables
WQandLilzoops = left_join(WQ_dataNARM, lilzoopsmean, by = c("Month", "Year", "Region")) %>%
  filter(Year >1999)
mat = dplyr::select(WQandLilzoops, Temperature, Secchi, Chlorophyll, Conductivity, lilzoopbiomass) %>%
  dplyr::filter(!is.na(Temperature), !is.na(Secchi), !is.na(Chlorophyll), !is.na(Conductivity), !is.na(lilzoopbiomass))
wqcorr = cor(as.matrix(mat))

corrplot.mixed(wqcorr, lower.col = c("blue", "red"))


#what's up with the 20mm zoop data?

twentymil = Zoopsynther(Data_type = "Community", Sources = "20mm")
summary(twentymil)
